name: Build RPM and DEB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build DEB Package
        run: |
          mkdir -p package_deb/usr/local/bin package_deb/DEBIAN
          cp count_files.sh package_deb/usr/local/bin/
          chmod +x package_deb/usr/local/bin/count_files.sh
          cp deb_control package_deb/DEBIAN/control
          dpkg-deb --build package_deb count-files.deb

      - name: Install RPM Tools
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Build RPM Package
        run: |
          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mkdir -p count-files-1.0
          cp count_files.sh count-files-1.0/
          tar -czvf rpmbuild/SOURCES/count-files-1.0.tar.gz count-files-1.0
          cp count-files.spec rpmbuild/SPECS/
          rpmbuild --define "_topdir $(pwd)/rpmbuild" -ba rpmbuild/SPECS/count-files.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: |
            *.deb
            rpmbuild/RPMS/**/*.rpm
